USE AutomotiveRepairSystem;

CREATE TABLE Service(
	ServiceId UNIQUEIDENTIFIER DEFAULT NEWID(),
	Name VARCHAR(50) NOT NULL,
	[Price (excl. VAT)] DECIMAL(10, 2) NOT NULL,
	CONSTRAINT Service_PK PRIMARY KEY (ServiceId),
	CONSTRAINT Service_UQ01_Name UNIQUE (Name)
)

CREATE TABLE Make(
	MakeId UNIQUEIDENTIFIER DEFAULT NEWID(),
	Name VARCHAR(75) NOT NULL,
	CONSTRAINT Make_PK PRIMARY KEY (MakeId),
	CONSTRAINT Make_UQ01_Name UNIQUE (Name)
)

CREATE TABLE Model(
	ModelId UNIQUEIDENTIFIER DEFAULT NEWID(),
	Name VARCHAR(75) NOT NULL,
	CONSTRAINT Model_PK PRIMARY KEY (ModelId),
	CONSTRAINT Model_UQ01_Name UNIQUE (Name)
)

CREATE TABLE Fuel(
	FuelId UNIQUEIDENTIFIER DEFAULT NEWID(),
	Name VARCHAR(50) NOT NULL,
	CONSTRAINT Fuel_PK PRIMARY KEY (FuelId),
	CONSTRAINT Fuel_UQ01_Name UNIQUE (Name)
)

CREATE TABLE Customer(
	CustomerId UNIQUEIDENTIFIER DEFAULT NEWID(),
	FirstName VARCHAR(25) NOT NULL,
	LastName VARCHAR(25) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	PhoneNumber VARCHAR(10) NOT NULL,
	CONSTRAINT Customer_PK PRIMARY KEY (CustomerId),
	CONSTRAINT Customer_UQ01_Email UNIQUE (Email),
	CONSTRAINT Customer_UQ02_PhoneNumber UNIQUE (PhoneNumber),
	CONSTRAINT Customer_CK01_Email CHECK (Email LIKE '%_@_%._%'),
	CONSTRAINT Customer_CK02_PhoneNumber CHECK (PhoneNumber LIKE '0[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
)

CREATE TABLE Vehicle(
	VehicleId UNIQUEIDENTIFIER DEFAULT NEWID(),
	LicensePlate VARCHAR(8) NOT NULL,
	Year DATE NOT NULL,
	VIN VARCHAR(17) NOT NULL,
	Mileage INT NOT NULL,
	MakeId UNIQUEIDENTIFIER NOT NULL,
	ModelId UNIQUEIDENTIFIER NOT NULL,
	FuelId UNIQUEIDENTIFIER NOT NULL,
	CustomerId UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT Vehicle_PK PRIMARY KEY (VehicleId),
	CONSTRAINT Vehicle_UQ01_LicensePlate UNIQUE (LicensePlate),
	CONSTRAINT Vehicle_FK01_Make FOREIGN KEY (MakeId) REFERENCES Make(MakeId) ON DELETE NO ACTION,
	CONSTRAINT Vehicle_FK02_Model FOREIGN KEY (ModelId) REFERENCES Model(ModelId) ON DELETE NO ACTION,
	CONSTRAINT Vehicle_FK03_Fuel FOREIGN KEY (FuelId) REFERENCES Fuel(FuelId) ON DELETE NO ACTION,
)

CREATE TABLE ServiceBatch(
	BatchId UNIQUEIDENTIFIER DEFAULT NEWID(),
	Complete SMALLINT NOT NULL DEFAULT 0,
	To_be_completed SMALLINT NOT NULL,
	Cancelled SMALLINT NOT NULL DEFAULT 0,
	CreatedAt DATE NOT NULL DEFAULT GETDATE(),
	Status VARCHAR(25) NOT NULL DEFAULT 'Scheduled',
	CONSTRAINT ServiceBatch_PK PRIMARY KEY (BatchId),
	CONSTRAINT ServiceBatch_CK01_Status CHECK (Status IN('Scheduled', 'In Progress', 'Split', 'Complete', 'Cancelled'))
)

CREATE TABLE ScheduledService(
	ScheduledServiceId UNIQUEIDENTIFIER DEFAULT NEWID(),
	Complete BIT NOT NULL DEFAULT 0,
	ScheduledDate DATE NOT NULL DEFAULT GETDATE(),
	AppointmentDate DATE NOT NULL,
	Status VARCHAR(25) NOT NULL DEFAULT 'Scheduled',
	VehicleId UNIQUEIDENTIFIER NOT NULL,
	ServiceId UNIQUEIDENTIFIER NOT NULL,
	BatchId UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT ScheduledService_PK PRIMARY KEY (ScheduledServiceId),
	CONSTRAINT ScheduledService_CK01_Status CHECK (Status IN('Scheduled', 'Complete', 'Invoiced', 'Cancelled')),
	CONSTRAINT ScheduledService_FK01_Vehicle FOREIGN KEY (VehicleId) REFERENCES Vehicle(VehicleId) ON DELETE NO ACTION,
	CONSTRAINT ScheduledService_FK02_Service FOREIGN KEY (ServiceId) REFERENCES Service(ServiceId) ON DELETE NO ACTION,
	CONSTRAINT ScheduledService_FK03_Batch FOREIGN KEY (BatchId) REFERENCES ServiceBatch(BatchId) ON DELETE NO ACTION
)

CREATE TABLE Invoice(
	InvoiceId UNIQUEIDENTIFIER DEFAULT NEWID(),
	CreationDate DATE NOT NULL DEFAULT GETDATE(),
	TotalAmount DECIMAL(10, 2) NOT NULL,
	AmountDue DECIMAL(10, 2) NOT NULL,
	Status VARCHAR(25) NOT NULL DEFAULT 'Not Sent',
	BatchId UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT Invoice_PK PRIMARY KEY (InvoiceId),
	CONSTRAINT Invoice_FK01_Batch FOREIGN KEY (BatchId) REFERENCES ServiceBatch(BatchId) ON DELETE NO ACTION,
	CONSTRAINT Invoice_CK01_Status CHECK (Status IN ('Not Sent', 'Sent', 'Partially Paid', 'Paid'))
)

CREATE TABLE Payment(
	PaymentId UNIQUEIDENTIFIER DEFAULT NEWID(),
	AmountPaid DECIMAL(10, 2) NOT NULL,
	PaymentDate DATE NOT NULL DEFAULT GETDATE(),
	PaymentMethod VARCHAR(25) NOT NULL,
	InvoiceId UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT Payment_PK PRIMARY KEY (PaymentId),
	CONSTRAINT Payment_FK01_Invoice FOREIGN KEY (InvoiceId) REFERENCES Invoice(InvoiceId) ON DELETE NO ACTION
)

